### ISSUE TITLE
Month is possibly off by one when stored to the RTC

### ISSUE THREAD

**Issue by realA10001986** [CircuitSetup/Time-Circuits-Display#14]
If I am not mistaken, the hardware RTC expects the month in the range from 1 to 12, not 0 to 11. TimeInfo, however, uses 0-11, so month needs to incremented before storing in getNTPTime(). 

Consequently, in clockDisplay::setMonth, the decrement of monthNum must be done regardless of isRTC.

**Comment by CircuitSetup** [comment]
This would explain a bug I was seeing with the days of the month not matching at the end of months. I'll have to test this. Thanks for pointing this out!

**Comment by CircuitSetup** [comment]
This is fixed in with PR #16
