### ISSUE TITLE
Add beep sound to sync with seconds led blink

### ISSUE THREAD

**Issue by CircuitSetup** [CircuitSetup/Time-Circuits-Display#3]
With the audio mixer library being used, there is a way to play 2 sounds at once, but it currently does not work. It may be necessary to not play the beep sound when a keypad tone or time travel sound is played. So...
- the beep sound only plays if other sounds are not played, and the beep option is turned on
- the beep sound should be played softer than other sounds as to not be totally annoying

**Comment by WMasterJedi** [comment]
> With the audio mixer library being used, there is a way to play 2 sounds at once, but it currently does not work. It may be necessary to not play the beep sound when a keypad tone or time travel sound is played. So...
> 
> * the beep sound only plays if other sounds are not played, and the beep option is turned on
> * the beep sound should be played softer than other sounds as to not be totally annoying

I would not mind that because the sound is only on for when you're typing on the keypad, and I wouldn't mind not having it for time travel either. Because the sound for the keypad is short and personally, I don't mind pausing the beeping for the time travel.

**Comment by CircuitSetup** [comment]
This is now included with v2.7
