### ISSUE TITLE
v2.6 Timer sound

### ISSUE THREAD

**Issue by doc1011** [CircuitSetup/Time-Circuits-Display#35]
Hi, using the new v2.6 speedo/sensors firmware.

When setting a timer, it seems to work and shows the correct remaining time when hitting 44Enter, but there is no sound/display once the timer runs out. 

Am using an SD card with 3.mp3 and 6.mp3 on it. Although using the speedo/sensors firmware there is none attached yet. 

Have I found a bug or is it me?

Cheers

**Comment by doc1011** [comment]
Sorry my fault for not reading the instructions closely enough - didn't realise there was a new sound file for the timer to upload :)

**Comment by CircuitSetup** [comment]
> Sorry my fault for not reading the instructions closely enough - didn't realise there was a new sound file for the timer to upload :)

yep! one new sound, so if you put **all of the files** from /software/data on an SD card, turn off TCD, put in card, turn TCD back on, it will load on startup.

**Comment by doc1011** [comment]
Works perfectly, thanks!
