### ISSUE TITLE
Allow music to be played from sd card

### ISSUE THREAD

**Issue by CircuitSetup** [CircuitSetup/Time-Circuits-Display#4]
- Add a settings menu option to play sounds/music from the SD card if mp3 files are detected. 
- Set a sound to play if a GPIO is pulled high. 13 and 14 have headers on the control board.

**Comment by jasonglisson** [comment]
I might be able to look into this. I just got my circuits and was looking over the documentation. I've got some experience triggering sounds with arduino in blasters and lightsabers that I've written code for. Really nice work on this kit by the way!

**Comment by CircuitSetup** [comment]
This can be done using the ESP8266Audio library that is used for other sounds, FYI. There is another file that would have to be included to do stuff from an SD card.

Glad you like the kit! Thanks!

**Comment by jasonglisson** [comment]
What are you thoughts about triggers for the music? We're you wanting
alarms or did you have something else in mind?

I'll have a look at the library. Several of the ones I've worked with
require mp3/wav files to be named 0000 or 0001 etc. And then some require
specific types of high speed SD cards in order to play multiple sounds at
the same time.

**Comment by CircuitSetup** [comment]
I was thinking this would work with an alarm that would allow setting the time for the alarm and setting the sound. In addition this could also be a stand alone music player, but it may be more useful as an alarm feature first.

I started to implement a web interface as well, but right now all it does is set the wifi credentials. Other fields are in there but they do not save properly yet. It may be easier to allow for setting time and sound files with this. Data is stored in the eeprom.

**Comment by CircuitSetup** [comment]
This was added in PR #16
