### ISSUE TITLE
Button Bracket / Lenses

### ISSUE THREAD

**Issue by TechieNetGuy** [CircuitSetup/Time-Circuits-Display#40]
I see that just today you published a new 3mf file for the lens bracket, I came here because the latest lenses I received didn't fit right.  So I assume this new bracket fixes that issue, but the 3mf when opened errors out in Cura with "No Models in File" error.

**Comment by TechieNetGuy** [comment]
Hey this is Alex....

I printed my own parts. Just the last 2 kits, the bracket won't snap in, and it at first glance looks like the taper on the colored lenses isn't allowing them to seat into the back of the green housing as well.  

I think the problem is the print of my keypad housing being a little off in the area of the lens "sockets". My initial thought was maybe you increased the countersink on the frame. 

Here are some pic's, and again I think the problem is me.  

First is the backside, and that is about where the lenses sit/bottom out without allowing the frame to snap into the housing.  I know the nuts are not installed, been trying several prints to get them to fit.

Second is the front showing the amount of exposed amount of the lenses through the face of the housing.  You can see they are not as proud of the front face of the keypad housing as typical.  The clear ones seem to seat properly (in any position), the colored ones cause the issues.  

My first thought was maybe this is a new batch of colored lenses?!  But I pulled out an older print (which I damaged a circuit board mount on), and these lenses seem to seat fine in that older print...so maybe something went wrong in my last 2 prints - and the clear lenses have more tolerance for a smaller hole.  


![IMG_2953](https://github.com/CircuitSetup/Time-Circuits-Display/assets/116675673/53cb63ac-b619-4d62-a9e0-7f2f56ea5f53)
![IMG_2955](https://github.com/CircuitSetup/Time-Circuits-Display/assets/116675673/fc57d61c-7ef8-4bba-af67-330db0daf186)

**Comment by CircuitSetup** [comment]
Hey Alex! I just double checked the fitments on my side with the latest batch of lenses and everything appears to fit as it should. It looks like you got one of the newer white lenses, but the others are from the last batch. 

It looks like the holes for the lenses in the keypad may be a bit too small. You can confirm this by checking the fitment of individual lenses without the white part. If they don't go in all the way, then try printing the keypad housing with a -0.04 horizontal expansion. 

If the lenses do fit individually, then try putting the top of the lens bracket (red) side first.
