### ISSUE TITLE
Click / Pop noise after each sound

### ISSUE THREAD

**Issue by dream7prod** [CircuitSetup/Time-Circuits-Display#41]
Hello,

There's an annoying click/pop noise after each sound. This noise is very notable on the new beep sound.

Seems to be some possible workarounds here: 
https://github.com/earlephilhower/ESP8266Audio/issues/476
and
https://github.com/earlephilhower/ESP8266Audio/issues/406

Thank you for your amazing work !

**Comment by dream7prod** [comment]
Version V2.8.0 (MAY222023)

**Comment by realA10001986** [comment]
Probably related to that darn 1.9.7 version of the audio lib.

I don't hear that noise, so it should be fixed in 2.9.

**Comment by dream7prod** [comment]
> Probably related to that darn 1.9.7 version of the audio lib.
> 
> I don't hear that noise, so it should be fixed in 2.9.

I installed your last version of the firmware and the click noise are gone ! 
Thank you !

**Comment by realA10001986** [comment]
Good to ....hear! ;)
