### ISSUE TITLE
timecircuits.local 

### ISSUE THREAD

**Issue by Backtothe1943x** [CircuitSetup/Time-Circuits-Display#42]
timecircuits.local isn't working and I was wondering when it will be back up in working order
![Screenshot_20231125-172019_Chrome](https://github.com/CircuitSetup/Time-Circuits-Display/assets/152042013/e87c4f5d-45ce-41c5-9945-74d239334b82)

**Comment by realA10001986** [comment]
timecircuits.local is the address under which you can reach the Config Portal of your Time Circuits Display, no public website. Your phone and the TCD must be in the same network. If your TCD is not connected to a WiFi network (which I assume is the case), connect your phone to the WiFi network "TCD-AP".

**Comment by Backtothe1943x** [comment]
oh ok thank you so much
