### ISSUE TITLE
Changing Hour problem

### ISSUE THREAD

**Issue by Gabin37** [CircuitSetup/Time-Circuits-Display#48]
Hi,

I wish to the hour the actual day, I go to the portal, I change the UTC time for france ( We added an hour to the time 2 weeks ago) and I Taped UTC+2 but it doesn't work :-/ 
Could you please help me? 

Regards

**Comment by realA10001986** [comment]
FIrst, don't use UTC+xxx timezones, the whole point of using time zones is for DST changes to happen automatically. The correct time zone for France is 

CET-1CEST,M3.5.0,M10.5.0/3

Secondly, you obviously are not using NTP for time synchronization, so a time zone change does not automatically change the time displayed. You need to go through the keypad menu to adjust your time manually.

**Comment by Gabin37** [comment]
Ok thanks a lot :)
I will do it with the keypad then.
How do I use NTP for time synchronization?
