### ISSUE TITLE
Enter button is not working.

### ISSUE THREAD

**Issue by FluxPower142** [CircuitSetup/Time-Circuits-Display#51]
Hello, I just received and assembled my time circuits display for the first time. The numbers on the keypad work but the enter button is not working or not even lighting up, is there something I’m missing or forgetting or is it faulty or broken?

**Comment by CircuitSetup** [comment]
I'm sorry it's giving you trouble. Is this with the keypad assembled, or when pressing the red button outside of the keypad housing, it does nothing?

**Comment by CircuitSetup** [comment]
Please open a support ticket on circuitsetup.us and we'll fix whatever is going on or get you a new control board.

**Comment by FluxPower142** [comment]
I submitted one
