### ISSUE TITLE
Car mode and BTTFN connection issue

### ISSUE THREAD

**Issue by gullwing12** [CircuitSetup/Time-Circuits-Display#52]
Have several other props in my vehicle with the TCD. TCD has been placed into car mode and BTTFN IP address has been updated to 192.168.4.1for each prop.  Now when displaying the connected devices via the TCD BTTFN clients it shows no connected devices found. If the TCD is connected to my home network then there are no issues connecting the props to each other via the BTTFN. Am I missing anything? Is there something other than the BTTFN IP address that needs to be changed when in car mode?

**Comment by gullwing12** [comment]
![20240803_190139](https://github.com/user-attachments/assets/032326d7-fe89-4a18-8047-cf99b03cdb6c)
![20240803_185957](https://github.com/user-attachments/assets/827f9049-6498-4422-8206-b74131fb9e6c)

**Comment by realA10001986** [comment]
The props need to connect to the TCD-AP WiFi network. I don't know in what WiFi mode the props are, probably in AP mode, so there is probably a SID-AP, FC-AP, DG-AP... WiFI network. Connect your computer/hand-held to the FC-AP (for example) WiFi network, navigate to 192.168.4.1 (which is the props IP address in AP mode), click on WiFi configuration, and connect the prop to the TCD-AP WiFi network.

**Comment by gullwing12** [comment]
Thanks working now
