### ISSUE TITLE
Print Instructions for Keypad Body

### ISSUE THREAD

**Issue by Ricky3Nut** [CircuitSetup/Time-Circuits-Display#8]
New user so apologies if this is not the right area...

But can you please explain what you mean in the README instructions for the _keypad_body_ where you say "...with top perpendicular to bed."? By the rest of the instructions I assume you mean to print key side up (back of body laying flat on the bed) so the front exposed surface can be ironed. But you also say 'iron top surface' so I assume you mean the side facing out with the keys vs the top of the body (which is attached to the bottom of the display enclosure). So if that is correct, then the top of the body is perperpendicular to the bed while the face is parallel, correct??? Its just that it seems the word "top" is used twice referring to 2 different surfaces and that is what is confusing me.

Sorry if that seems obvious and I am over-thinking it but it just got me a little confused.

Thanks!

**Comment by CircuitSetup** [comment]
Sorry, that definitely should say "with top **parallel** to bed".

here is what it looks like in Cura:
![keypad_cura](https://user-images.githubusercontent.com/34163498/137414167-20733e5d-621e-45d9-9ae7-9df379819d98.png)

The keypad bezel top should also be parallel to the bed. 

I'll add the .3mf cura files for these in the 3d files folder.
