### ISSUE TITLE
After time traveling a 0 is inserted into the date entry buffer

### ISSUE THREAD

**Issue by CircuitSetup** [CircuitSetup/Time-Circuits-Display#9]
The date entry buffer is getting a 0 inserted after time traveling, causing the next entered date to be incorrect.

**Comment by realA10001986** [comment]
I think that can be fixed as follows, in tc_keypad.cpp:

Somewhere at the top, insert:

bool doKey = false;

Then replace the keypadEvent function with the following code:

// handle different cases for keypresses
void keypadEvent(KeypadEvent key) {
    switch (keypad.getState()) {
        case PRESSED:
            if(key != '#' && key != '*') {
                play_keypad_sound(key);
            }
            doKey = true;            
            break;        
        case HOLD:            
            if(key == '0') {
                doKey = false;
                timeTravel();                
            }
            break;
        case RELEASED:
            if(doKey && key != '#' && key != '*') {
                if(isSetUpdate) {
                    recordSetTimeKey(key);
                } else {
                    recordKey(key);
                }
            }
            break;
        case IDLE:
            break;
    }
}

This way, the held "0" key is not inserted into the buffer.

**Comment by CircuitSetup** [comment]
This is fixed in PR #16
Thanks!
